// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;
// pragma experimental ABIEncoderV2;

/* ToDo : Use Ownable OpenZeppelin */
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/math/SafeMath.sol";

// import "./LotteryGenerator.sol";
import "./VRFv2Consumer.sol";
import "./VRFv2SubscriptionManager.sol";

import "./LotteryCore.sol";

// import "truffle/Console.sol";
// import "hardhat/console.sol";


interface IilotteryGenerator {
    function LotteryWinnersArray() external view returns (address[] memory);
    function setlotteryStructs(address _lotteryAddress, uint _totalBalance, address _winnerAddress, uint8 _lotteryType) external returns (bool);
    function setWeeklyWinnersArrayMap(address _lotteryAddress, address _winnerAddress) external returns (uint);
    function clearlotteryWinnersArrayMap(address _lotteryAddress) external returns (bool);
}


/**
************************************************************************************
************************************************************************************


/**
************************************************************************************
************************************************************************************
**/
/**
  * @title Weekly Lottery For BSC Lottery Game 
  * @author Batis 
  * @notice This SmartContract is responsible for implimentation of Weekly Pot Lottery 
  * @dev WeeklyLottery will be Generated by LotteryGenerator
*/
contract WeeklyLottery is Ownable {

  address private _VRF;
  address private generatorLotteryAddr;
  address[] private _LotteryWinnersArray;
  address public MonthlyPotAddress;   

  event SelectWinnerIndex(uint winnerIndex, uint potBalance, uint winnerPrize);
  event SelectWinnerAddress(address potWinner, uint winnerPrize);
  event TotalPayment(address receiver, uint TrxValue);

  constructor(address VRF) {   // , address lOwner
    _VRF = VRF;
  }

  fallback() external payable {
  }
  receive() external payable {
  }

  function balanceInPot() public view returns(uint){
    return address(this).balance;
  }

  function withdraw() external onlyOwner {
    payable(msg.sender).transfer(address(this).balance);
  }

  function getRandomValue(address _VRFv2) public view onlyOwner returns (uint256 randomWords) {
    // uint8 zeroOne = uint8(randomGenerator() % 2);
    randomWords = VRFv2Consumer(_VRFv2).getlRandomWords();
  }

  /* ToDo : Replace This function with OpenZeppelin SafeMath */
  /**
    * @notice Function for deviding two Integer Numbers and return the results.
    * @dev Safe Function for Devision Operation.
    * @param numerator : The Integer Number which is being devided on another Integer Number.
    * @param denominator : The Integer Number which another Int NUmber is devided by this.  
    * @return quotient and remainder of the Devision, Both are Integer Numbers. 
  */
  function getDivided(uint numerator, uint denominator) public pure returns(uint quotient, uint remainder) {
    require( denominator >= 0, "Division is Not Possible , Bug in Numbers !");
    require( numerator > 0, "Division is Not Possible , Bug in Numbers !");
    quotient  = numerator / denominator; 
    remainder = numerator - denominator * quotient;
  }

  function getLotteryWinnersArray() internal view returns(address[] memory) {
    return IilotteryGenerator(generatorLotteryAddr).LotteryWinnersArray();
  }

  function select_Winner() public onlyOwner {  

    _LotteryWinnersArray = getLotteryWinnersArray();  
    uint256 l_randomWords = getRandomValue(_VRF);
    uint winnerIndex = l_randomWords % _LotteryWinnersArray.length;
    uint winnerPrize = Calculation();
    
    emit SelectWinnerIndex(winnerIndex, address(this).balance, winnerPrize);
    
    UpdateLotteryData(winnerIndex, address(this).balance);
    WinnerPrizePayment(winnerIndex, winnerPrize); 
    FinalPayment();
    ClearDataBase();

  }

  /**
    * @notice Release Smart Contract Memory .
    * @dev Clear All Storages .
  */
  function ClearDataBase() internal returns (bool) {
    bool _success;
    _success = IilotteryGenerator(generatorLotteryAddr).clearlotteryWinnersArrayMap(address(this));
    return true;
  }

  /**
    * @notice Calculation of Pot Winner Prize.
    * @dev Findout the 5% of the Total Pot and The Winner payment.
  */
  function Calculation() internal view returns (uint winnerPrize){

    uint totalPot = address(this).balance;
    // _LotteryWinnersArray = getLotteryWinnersArray();  
    // address WinnerAddress = _LotteryWinnersArray[_winnerIndex];
    /* ToDo : Replace Calculation Parts with OpenZeppelin SafeMath ) */
    (winnerPrize, ) = getDivided(totalPot, 20);  // winnerPrize

  }

  /**
    * @notice Pay Pot Prize to the Winner.
    * @dev Transfer Pot Prize to the Winner.
  */
  function WinnerPrizePayment(uint _winnerIndex, uint _winnerPrize) internal {

    // _LotteryWinnersArray = getLotteryWinnersArray();  
    address payable potWinner = payable(_LotteryWinnersArray[_winnerIndex]);  
    potWinner.transfer(_winnerPrize);
    emit SelectWinnerAddress(potWinner, _winnerPrize);
    // _LotteryWinnersArray[winnerIndex].transfer(address(this).balance);

  }

  /**
    * @notice Remaining Pot Money Transfer.
    * @dev Transfer remaining Money to the Liquidity Pool.
  */
  function FinalPayment() internal {   //  onlyOwner

    address payable receiver = payable(MonthlyPotAddress);
    uint TrxValue = address(this).balance;
    receiver.transfer(TrxValue);
    emit TotalPayment(receiver, TrxValue);

  }

  function set_MonthlyPotAddress(address _MonthlyPotAddress) external onlyOwner {
    require(_MonthlyPotAddress != address(0) );
    MonthlyPotAddress = _MonthlyPotAddress;
  }

  /**
    * @notice Save The Winner Address for Weekly Lottery
    * @dev Update Generator Smart Contract For Saving Hourly Winner Address
  */
  function UpdateLotteryData(uint _winnerIndex, uint _balance) internal returns(bool) {
    bool _success;
    uint _winnerId;
    // _LotteryWinnersArray = getLotteryWinnersArray();  
    address _winnerAddress = _LotteryWinnersArray[_winnerIndex];
    _success = IilotteryGenerator(generatorLotteryAddr).setlotteryStructs(address(this), _balance, _winnerAddress, 2);
    _winnerId = IilotteryGenerator(generatorLotteryAddr).setWeeklyWinnersArrayMap(address(this), _winnerAddress);
    return true;
  }

  function generatorLotteryAddress(address _contractAddr) external onlyOwner {
    generatorLotteryAddr = _contractAddr;
  }

}

/**
************************************************************************************
************************************************************************************
**/


